"""
ReAct Agent — Reasoning + Acting Loop
======================================
Demonstrates the ReAct (Reason → Act → Observe) loop with fake tools:
  - calculator  : evaluates arithmetic expressions
  - search      : returns canned "web search" results

The agent solves a multi-step word problem by interleaving thought and action,
producing a full reasoning trace.

Run:
    python3 examples/react_agent/main.py

No external dependencies required.
"""

import re
from dataclasses import dataclass, field
from typing import Optional


# ── Tool registry ──────────────────────────────────────────────────────────────

@dataclass
class ToolResult:
    tool: str
    input: str
    output: str


def tool_calculator(expr: str) -> str:
    """Safely evaluate a simple arithmetic expression including round()."""
    # Strip all allowed tokens; if anything remains it's unsafe
    stripped = re.sub(r"(\d+\.?\d*|[\s\+\-\*\/\(\),]|round)", "", expr)
    if stripped:
        return f"ERROR: unsafe expression '{expr}'"
    try:
        result = eval(expr, {"__builtins__": {}, "round": round})   # noqa: S307
        return str(result)
    except Exception as e:
        return f"ERROR: {e}"


SEARCH_DB = {
    "population of france": "France has a population of approximately 68 million people (2024).",
    "gdp of france": "France's GDP is approximately $3.0 trillion USD (2024 estimate).",
    "population of germany": "Germany has a population of approximately 84 million people (2024).",
    "gdp per capita france": "France's GDP per capita is approximately $44,000 USD.",
}

def tool_search(query: str) -> str:
    """Return a canned search result for known queries."""
    key = query.strip().lower()
    for k, v in SEARCH_DB.items():
        if k in key or key in k:
            return v
    return f"No result found for: '{query}'"


TOOLS = {
    "calculator": tool_calculator,
    "search":     tool_search,
}


# ── ReAct loop ─────────────────────────────────────────────────────────────────

@dataclass
class Step:
    thought:    str
    action:     Optional[str]    # "tool_name: input"
    observation: Optional[str]


class ReActAgent:
    """
    Minimal ReAct loop. In production, the LLM generates thought/action text;
    here we hard-code the reasoning trace to show the pattern clearly.
    """

    def __init__(self, max_steps: int = 10):
        self.max_steps = max_steps
        self.trace: list[Step] = []

    def run(self, question: str, scripted_steps: list[dict]) -> str:
        """
        Execute the scripted reasoning trace and return the final answer.

        In a real system, each thought/action would be generated by an LLM call.
        The scripted_steps parameter simulates that output deterministically.
        """
        print(f"Question: {question}\n")

        for i, s in enumerate(scripted_steps, start=1):
            thought     = s.get("thought", "")
            action_str  = s.get("action")        # e.g. "search: population of france"
            is_final    = s.get("final", False)

            print(f"Step {i}")
            print(f"  Thought    : {thought}")

            if is_final:
                # The action field holds the final answer when is_final=True
                print(f"  Answer     : {action_str}")
                self.trace.append(Step(thought=thought, action=None, observation=action_str))
                return action_str

            # Parse "tool_name: input"
            tool_name, _, tool_input = (action_str or "").partition(":")
            tool_name  = tool_name.strip()
            tool_input = tool_input.strip()

            print(f"  Action     : {tool_name}({tool_input!r})")

            # Execute the tool
            if tool_name in TOOLS:
                observation = TOOLS[tool_name](tool_input)
            else:
                observation = f"Unknown tool: {tool_name}"

            print(f"  Observation: {observation}\n")

            self.trace.append(Step(
                thought=thought,
                action=action_str,
                observation=observation,
            ))

        return "Max steps reached without final answer."


# ── Demo harness ───────────────────────────────────────────────────────────────

def demo():
    agent = ReActAgent(max_steps=10)

    question = (
        "What is the combined population of France and Germany, "
        "and what percentage does France represent?"
    )

    # Scripted trace — simulates what an LLM would generate step by step
    scripted_steps = [
        {
            "thought": "I need the population of France first.",
            "action":  "search: population of france",
        },
        {
            "thought": "I have France's population (68M). Now I need Germany's.",
            "action":  "search: population of germany",
        },
        {
            "thought": "Both numbers are ready. I'll compute the combined total.",
            "action":  "calculator: 68 + 84",
        },
        {
            "thought": "Combined is 152M. Now I'll compute France's share as a percentage.",
            "action":  "calculator: round(68 / 152 * 100, 1)",
        },
        {
            "thought": (
                "I have all the data: combined=152M, France=68M which is ~44.7%. "
                "I can now give the final answer."
            ),
            "action": (
                "The combined population of France and Germany is approximately 152 million. "
                "France accounts for roughly 44.7% of that total."
            ),
            "final": True,
        },
    ]

    print("=" * 60)
    print("ReAct Agent — Reasoning Trace")
    print("=" * 60)
    print()

    answer = agent.run(question, scripted_steps)

    print()
    print("=" * 60)
    print(f"Final Answer: {answer}")
    print(f"Steps taken : {len(agent.trace)}")
    print("=" * 60)


if __name__ == "__main__":
    demo()
