"""
LORE SCAFFOLD: cost_guard — Hard-Stop Cost Protection for Production AI Agents

The Timekeeper's budget enforcer. Tracks token consumption per step, warns at
configurable thresholds, and raises CostGuardExceeded before an agent can
silently burn through its entire budget.

Cost guards missing in 10/10 production agent repos audited. This is the fix.

Generated by: lore scaffold cost_guard
Docs: https://github.com/miles-lore/lore

Usage:
    guard = CostGuard(budget_tokens=100_000, warn_at=0.80)
    guard.consume("llm_call", tokens=2_400)
    guard.warn_if_low()    # logs warning if >80% used
    print(guard.summary()) # full budget breakdown
"""

import logging
import time
from typing import Any

logger = logging.getLogger(__name__)


class CostGuardExceeded(Exception):
    """Raised when the agent's token budget is exhausted.

    Attributes:
        used: Total tokens consumed at the point of failure.
        budget: The configured hard-stop budget.
        step: The step name that triggered the exception.
    """

    def __init__(self, used: int, budget: int, step: str = "") -> None:
        self.used = used
        self.budget = budget
        self.step = step
        pct = 100.0 * used / budget if budget else 0.0
        where = f" at step '{step}'" if step else ""
        super().__init__(
            f"CostGuard: budget exhausted{where} — used {used:,} / {budget:,} tokens ({pct:.1f}%)"
        )


class CostGuard:
    """Hard-stop cost protection for production AI agents.

    Generated by: lore scaffold cost_guard
    Docs: https://github.com/miles-lore/lore

    Tracks token consumption step-by-step, emits a warning when the warn
    threshold is crossed, and raises CostGuardExceeded when the hard budget
    is hit. Zero external dependencies — drop into any Python agent project.

    Args:
        budget_tokens: Hard-stop limit. Raises CostGuardExceeded when exceeded.
        warn_at: Fraction of budget that triggers a warning log (default 0.80).
        name: Optional label for this guard, used in log messages.

    Example::

        guard = CostGuard(budget_tokens=100_000, warn_at=0.80)

        for step_name, prompt in steps:
            tokens = call_llm(prompt)
            guard.consume(step_name, tokens)
            guard.warn_if_low()

        print(guard.summary())
    """

    def __init__(
        self,
        budget_tokens: int = 100_000,
        warn_at: float = 0.80,
        name: str = "default",
    ) -> None:
        if budget_tokens <= 0:
            raise ValueError(f"budget_tokens must be positive, got {budget_tokens}")
        if not 0.0 < warn_at < 1.0:
            raise ValueError(f"warn_at must be between 0 and 1 (exclusive), got {warn_at}")

        self.budget = budget_tokens
        self.warn_at = warn_at
        self.name = name
        self._used: int = 0
        self._warned: bool = False
        self._step_log: list[dict[str, Any]] = []
        self._started_at: float = time.monotonic()

    # ── Core API ──────────────────────────────────────────────────────────────

    def consume(self, step: str, tokens: int) -> None:
        """Record token consumption for a named step.

        Appends an entry to the step log, increments the running total, then
        calls :meth:`check` to raise :exc:`CostGuardExceeded` if the budget
        is now exhausted.

        Args:
            step: Human-readable name for this step (e.g. "llm_call", "tool_use").
            tokens: Number of tokens consumed by this step.

        Raises:
            ValueError: If *tokens* is negative.
            CostGuardExceeded: If the running total now exceeds the budget.
        """
        if tokens < 0:
            raise ValueError(f"tokens must be non-negative, got {tokens}")

        self._used += tokens
        self._step_log.append(
            {
                "step": step,
                "tokens": tokens,
                "cumulative": self._used,
                "ts": time.monotonic() - self._started_at,
            }
        )
        self.check(step=step)

    def check(self, step: str = "") -> None:
        """Raise CostGuardExceeded if the budget is exhausted.

        Safe to call at any point in an agent loop as a standalone guard —
        does nothing if within budget.

        Raises:
            CostGuardExceeded: If ``_used >= budget``.
        """
        if self._used >= self.budget:
            raise CostGuardExceeded(used=self._used, budget=self.budget, step=step)

    def warn_if_low(self) -> bool:
        """Emit a warning log if more than *warn_at* fraction of budget is used.

        Only fires once — subsequent calls within the same guard instance are
        no-ops after the first warning.

        Returns:
            True if a warning was emitted on this call, False otherwise.
        """
        if self._warned:
            return False
        if self._used >= self.warn_at * self.budget:
            pct = 100.0 * self._used / self.budget
            remaining = self.budget - self._used
            logger.warning(
                "CostGuard[%s]: %.1f%% of budget used (%d / %d tokens). "
                "%d tokens remaining before hard stop.",
                self.name,
                pct,
                self._used,
                self.budget,
                remaining,
            )
            self._warned = True
            return True
        return False

    def summary(self) -> dict[str, Any]:
        """Return a full budget breakdown as a plain dict.

        Returns a dictionary with keys:
            - ``name``: guard label
            - ``budget``: hard-stop limit
            - ``used``: total tokens consumed
            - ``remaining``: tokens left
            - ``pct_used``: percentage used (0–100)
            - ``warn_at_pct``: warning threshold as percentage
            - ``warned``: whether the warning has fired
            - ``steps``: number of recorded steps
            - ``step_log``: list of per-step records
            - ``elapsed_seconds``: wall-clock seconds since guard was created
        """
        elapsed = time.monotonic() - self._started_at
        return {
            "name": self.name,
            "budget": self.budget,
            "used": self._used,
            "remaining": max(0, self.budget - self._used),
            "pct_used": round(100.0 * self._used / self.budget, 2) if self.budget else 0.0,
            "warn_at_pct": round(self.warn_at * 100, 1),
            "warned": self._warned,
            "steps": len(self._step_log),
            "step_log": list(self._step_log),
            "elapsed_seconds": round(elapsed, 3),
        }

    # ── Convenience helpers ───────────────────────────────────────────────────

    @property
    def used(self) -> int:
        """Total tokens consumed so far."""
        return self._used

    @property
    def remaining(self) -> int:
        """Tokens remaining before hard stop."""
        return max(0, self.budget - self._used)

    @property
    def pct_used(self) -> float:
        """Percentage of budget consumed (0.0–100.0)."""
        return 100.0 * self._used / self.budget if self.budget else 0.0

    def reset(self) -> None:
        """Reset the guard to zero — useful for testing or per-request guards."""
        self._used = 0
        self._warned = False
        self._step_log = []
        self._started_at = time.monotonic()

    def __repr__(self) -> str:
        return (
            f"CostGuard(name={self.name!r}, used={self._used}, "
            f"budget={self.budget}, pct={self.pct_used:.1f}%)"
        )
